services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 1s
      timeout: 5s
      retries: 10

  bun_hono_app:
    build: ./bun_hono
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PGHOST: postgres
      PGDATABASE: docker
      PGUSER: docker
      PGPASSWORD: docker
      PGPORT: 5432
      MONGO_URI: mongodb://host.docker.internal:26115
      MONGO_DB_NAME: local

volumes:
  postgres-data:
